import { Navbar } from "@/app/components/Navbar";
import Logo from "@/app/components/Logo";
import Link from "next/link";
import Image from "next/image";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function MainLayout({ children }) {

  return (
    <>
      <Navbar
        brand={
          <Link href="/" className="flex items-center">
            <Logo />
            <p className="font-black font-nunito text-5xl">
              <span className="text-accent">Pet</span>
              <span className="text-primary">Nearly</span>
            </p>
          </Link>
        }
        className="bg-neutral"
        items={[
          { label: "Home", href: "/" },
          { label: "All Pets", href: "/all-pets" },
        ]}
        rightContent={
          <>
            <Link
              className="bg-accent py-2 px-4 text-white cursor-pointer hover:bg-accent/90 transition-colors delay-100"
              href="/login"
            >
              Login
            </Link>
            <Link
              className="bg-primary py-2 px-4 text-white cursor-pointer hover:bg-primary/90 transition-colors delay-100"
              href="/signup"
            >
              Sign Up
            </Link>
          </>
        }
        subImage={
          <div className=" h-10 w-full fixed top-18 z-20">
            <Image src="/menu_strip.png" alt="Logo" fill loading="eager" />
          </div>
        }
      />
      {children}
    </>
  );
}
