import { Nunito, Poppins } from "next/font/google";
import "./globals.css";
import { Navbar } from "@/components/Navbar";
import Logo from "@/components/Logo";
import Link from "next/link";
import { Button } from "@heroui/react";

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800", "900"],
});

const nunito = Nunito({
  variable: "--font-nunito",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800", "900"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  return (
    <html
      lang="en"
      className={`${poppins.variable} ${nunito.variable} h-full antialiased`}
    >
      <body suppressHydrationWarning>
        <Navbar
          brand={
            <Link href="/" className="flex items-center">
              <Logo />
              <p className="font-black font-nunito text-5xl"> <span className="text-accent">Pet</span><span className="text-primary">Nearly</span></p>
            </Link>


          }
          className="bg-neutral"
          items={[
            { label: "Home", href: "/" },
            { label: "All Pets", href: "/all-pets" },
          ]}
          rightContent={
            <>
              <Link className="bg-accent py-2 px-4 text-white cursor-pointer hover:bg-accent/90 transition-colors delay-100" href="/login">
                Login
              </Link>
              <Link className="bg-primary py-2 px-4 text-white cursor-pointer hover:bg-primary/90 transition-colors delay-100" href="/signup">
                Sign Up
              </Link>
            </>
          }
        />
        {children}</body>
    </html>
  );
}
